edition = "2024"
style_edition = "2024"
unstable_features = true

max_width = 80

enum_discrim_align_threshold = 20
struct_field_align_threshold = 4

format_macro_bodies = true
format_strings = true

hex_literal_case = "Upper"

overflow_delimited_expr = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
