on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run:  rustup toolchain install nightly --profile minimal
      - name: Install rustfmt
        run:  rustup component add rustfmt
  fmt:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - run: cargo fmt --check
  check:
    runs-on: ubuntu-latest
    needs: [ setup_rust, fmt ]
    steps:
      - run: cargo check
  test:
    runs-on: ubuntu-latest
    needs: [ setup_rust, fmt ]
    steps:
      - run: cargo test
