name: Validate code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fmt-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --check
  check:
    name: Check build and run tests
    runs-on: ubuntu-latest
    needs: [ fmt-check ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run:  sudo apt-get update
      - run:  sudo apt-get install -yqq libasound2-dev
      - run:  cargo test
